# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-09 08:07
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('overview', models.CharField(max_length=1000)),
                ('hotcount', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=base.models.productphotoname)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=5000)),
                ('creator_name', models.CharField(max_length=70)),
                ('creator_contact_no', models.IntegerField(blank=True, default=91, null=True)),
                ('creator_email', models.EmailField(max_length=254)),
                ('creator_rating', models.CharField(choices=[('5', 'Very Good'), ('4', 'Good'), ('3', 'Average'), ('2', 'Poor'), ('1', 'Very Poor')], default='5', max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.reviewphotoname)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Review')),
            ],
        ),
    ]
